// Writes the landing page for the published reference, from the versions
// that are actually there.
//
// It is a landing page first and a version index second. Most arrivals come
// from npm, a search result or the README badge and have never seen the
// library, so the page says what it is and what it has that the obvious
// alternative does not, then routes to the reference. It does not document
// the API -- that is what it links to, and a summary here would be a second
// copy that nothing regenerates.
//
// Generated rather than committed, and generated by reading the directory
// rather than a list: a hand-kept list of versions is wrong the first time a
// release is added and nothing reports it, where this cannot describe a
// version that is not published or omit one that is.
//
// Usage: node site-index.mjs <site-dir>

import { readdirSync, writeFileSync, existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

const site = process.argv[2];
if (!site || !existsSync(site)) {
  console.error("Usage: node site-index.mjs <site-dir>");
  process.exit(1);
}

/// Sorts `v5.10.0` above `v5.9.0`, which a string comparison does not.
function order(a, b) {
  const parts = (v) => v.slice(1).split(".").map(Number);
  const [x, y] = [parts(a), parts(b)];
  return y[0] - x[0] || y[1] - x[1] || y[2] - x[2];
}

const versions = readdirSync(site, { withFileTypes: true })
  .filter((entry) => entry.isDirectory() && /^v\d+\.\d+\.\d+$/.test(entry.name))
  .map((entry) => entry.name)
  .sort(order);

if (versions.length === 0) {
  console.error("No versions in the site directory; nothing to index.");
  process.exit(1);
}

// `latest` is a copy of a version rather than a symlink, because the Pages
// artifact is a tarball and a symlink in it resolves to nothing. Which
// version it copies is recorded here so this page can say so.
const stampFile = join(site, "latest", "VERSION");
const latest = existsSync(stampFile)
  ? readFileSync(stampFile, "utf8").trim()
  : versions[0];

const older = versions
  .filter((version) => version !== latest)
  .map((version) => `        <li><a href="${version}/">${version}</a></li>`)
  .join("\n");

// What a reader who has never used this library needs in the first screen.
// Every claim here is one the README states and the declarations carry; if
// one stops being true, it is wrong in three places at once, which is the
// point -- a claim only this page makes has nothing to check it.
const features = [
  [
    "Float compositing",
    "<code>RGBAF16</code> and <code>RGBAF32</code> composite in float rather " +
      "than merely reading back in it, so stacked translucent layers do not " +
      "accumulate rounding error.",
  ],
  [
    "Wide gamut and HDR transfer functions",
    "Fifteen names across eight spaces &mdash; sRGB, Display P3, Rec.&nbsp;2020, " +
      "HDR10 (PQ), HLG and linear variants. A canvas composites in the space " +
      "you name and exports tagged with it.",
  ],
  [
    "CSS Color 4, and OkLab gradients",
    "<code>oklch()</code>, <code>lab()</code> and <code>color()</code> parse " +
      "wherever a colour is taken, and a gradient interpolates in the space " +
      "you choose &mdash; <code>oklab</code> holds lightness where sRGB goes " +
      "muddy in the middle.",
  ],
  [
    "Eleven export formats",
    "PNG, JPEG, WebP, GIF, APNG, TIFF, ICO, BMP, AVIF, PDF and SVG. Pages are " +
      "frames: the four formats that carry a clock write animations, and an " +
      "animation read back reports its own frames and delays.",
  ],
  [
    "Typography that goes past <code>fillText</code>",
    "Variable font axes, OpenType features, word wrap with per-line metrics, " +
      "and a <code>ParagraphBuilder</code> for rich text with mixed styles, " +
      "per-run shadows and hit testing.",
  ],
  [
    "GPU rendering",
    "Metal on macOS, Vulkan elsewhere, chosen per canvas. " +
      "<code>canvas.engine</code> reports which backend took it, the adapter, " +
      "and why the GPU was declined when it was.",
  ],
  [
    "Path geometry and filters",
    "Boolean operations, <code>trim</code>, <code>interpolate</code>, 3D " +
      "projection and vector textures, plus the CSS filter set and " +
      "CanvasKit's <code>ColorFilter</code>, <code>ImageFilter</code>, " +
      "<code>MaskFilter</code> and <code>Shader</code>.",
  ],
  [
    "On-screen as well as off",
    "<code>Window</code> and <code>App</code> give a browser-like event loop, " +
      "from Rust as well as Node.",
  ],
]
  .map(
    ([title, body]) =>
      `      <li>\n        <h3>${title}</h3>\n        <p>${body}</p>\n      </li>`,
  )
  .join("\n");

// Wide colour and a float canvas in seven lines, because those are the two
// things a reader is here to find out this library has. Nothing in it is
// specific to a version, so it does not go stale between releases.
const sample = `import { Canvas } from "meo-skia-canvas";

let canvas = new Canvas(1920, 1080, {
    colorType: "RGBAF16", // composites in float, not just reads back in it
    colorSpace: "display-p3", // or rec2020, rec2020-pq, srgb-linear, ...
  }),
  ctx = canvas.getContext("2d");

ctx.fillStyle = "oklch(70% 0.28 25)"; // outside sRGB, and kept
ctx.fillRect(0, 0, 1920, 1080);

await canvas.toFile("out.png"); // 16 bits a channel, tagged P3`;

writeFileSync(
  join(site, "index.html"),
  `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>meo-skia-canvas — the HTML Canvas API on Skia</title>
    <meta
      name="description"
      content="The HTML Canvas 2D API for Node and Rust, on Google's Skia: float compositing, wide-gamut and HDR colour spaces, eleven export formats, GPU rendering, and rich text layout."
    />
    <style>
      :root {
        color-scheme: light dark;
        --accent: #1d4ed8;
        --rule: color-mix(in srgb, currentColor 18%, transparent);
        --hush: color-mix(in srgb, currentColor 8%, transparent);
      }
      @media (prefers-color-scheme: dark) {
        :root { --accent: #93b8ff; }
      }
      * { box-sizing: border-box; }
      body {
        margin: 0 auto; padding: 3rem 1.5rem 4rem; max-width: 46rem;
        font: 16px/1.6 ui-sans-serif, system-ui, -apple-system, sans-serif;
      }
      h1 { margin: 0 0 0.15rem; font-size: 1.7rem; letter-spacing: -0.01em; }
      p.tagline { margin: 0 0 1rem; font-size: 1.15rem; font-weight: 600; }
      p.lede { margin: 0; opacity: 0.8; }
      p.lede code { font-size: 0.95em; }

      a { color: var(--accent); }
      code {
        font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
        font-size: 0.9em;
      }

      .latest {
        display: block; margin: 1.75rem 0; padding: 1rem 1.25rem;
        border: 1px solid var(--rule); border-radius: 8px;
        text-decoration: none; font-weight: 600; color: inherit;
      }
      .latest b { color: var(--accent); }
      .latest span {
        display: block; margin-top: 0.15rem;
        font-weight: 400; opacity: 0.7; font-size: 0.9rem;
      }

      h2 {
        margin: 2.5rem 0 0.75rem; font-size: 0.8rem; text-transform: uppercase;
        letter-spacing: 0.08em; opacity: 0.6;
      }

      pre {
        margin: 0; padding: 1rem 1.15rem; overflow-x: auto;
        background: var(--hush); border-radius: 8px;
        font: 0.85rem/1.55 ui-monospace, SFMono-Regular, Menlo, monospace;
      }
      pre .c { opacity: 0.6; }

      ul.features { list-style: none; margin: 1.75rem 0 0; padding: 0; display: grid; gap: 1.6rem 2rem;
        grid-template-columns: repeat(auto-fit, minmax(17rem, 1fr)); }
      ul.features h3 { margin: 0 0 0.2rem; font-size: 0.98rem; }
      ul.features p { margin: 0; font-size: 0.92rem; opacity: 0.8; }

      /* auto-fill rather than a fixed count: the list is as many columns as
         fit, down to one on a phone, without a breakpoint to keep in step
         with however many versions are published. */
      ul.versions { list-style: none; margin: 0; padding: 0; display: grid;
        gap: 0.15rem 1rem;
        grid-template-columns: repeat(auto-fill, minmax(7rem, 1fr)); }

      footer {
        margin-top: 3rem; padding-top: 1.25rem; border-top: 1px solid var(--rule);
        font-size: 0.9rem;
      }
      footer a { margin-right: 1.25rem; display: inline-block; }
    </style>
  </head>
  <body>
    <h1>meo-skia-canvas</h1>
    <p class="tagline">The HTML Canvas 2D API on Skia, for Node and Rust.</p>
    <p class="lede">
      Google's Skia underneath, so output matches Chrome's
      <code>&lt;canvas&gt;</code> closely &mdash; and then a good deal a browser
      canvas cannot do. One implementation, two surfaces: the same method names
      and argument order from JavaScript and from Rust.
    </p>

    <a class="latest" href="latest/">
      JavaScript API reference &mdash; <b>${latest}</b>
      <span>Generated from the type declarations the package ships. Always at <code>latest/</code>.</span>
    </a>

    <h2>What you get</h2>
    <pre><code>${sample
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/(\/\/.*)$/gm, '<span class="c">$1</span>')}</code></pre>

    <ul class="features">
${features}
    </ul>

${older ? `    <h2>Earlier releases</h2>\n    <ul class="versions">\n${older}\n    </ul>` : ""}

    <footer>
      <a href="https://github.com/l7aromeo/meo-skia-canvas#readme">Guide and README</a>
      <a href="https://docs.rs/meo-skia-canvas">Rust reference</a>
      <a href="https://www.npmjs.com/package/meo-skia-canvas">npm</a>
      <a href="https://github.com/l7aromeo/meo-skia-canvas">Source</a>
    </footer>
  </body>
</html>
`,
);

console.log(`Indexed ${versions.length} version(s); latest is ${latest}.`);
