// Writes the landing page for the published reference, from the versions
// that are actually there.
//
// Generated rather than committed, and generated by reading the directory
// rather than a list: a hand-kept list of versions is wrong the first time a
// release is added and nothing reports it, where this cannot describe a
// version that is not published or omit one that is.
//
// Usage: node site-index.mjs <site-dir>

import { readdirSync, writeFileSync, existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

const site = process.argv[2];
if (!site || !existsSync(site)) {
  console.error("Usage: node site-index.mjs <site-dir>");
  process.exit(1);
}

/// Sorts `v5.10.0` above `v5.9.0`, which a string comparison does not.
function order(a, b) {
  const parts = (v) => v.slice(1).split(".").map(Number);
  const [x, y] = [parts(a), parts(b)];
  return y[0] - x[0] || y[1] - x[1] || y[2] - x[2];
}

const versions = readdirSync(site, { withFileTypes: true })
  .filter((entry) => entry.isDirectory() && /^v\d+\.\d+\.\d+$/.test(entry.name))
  .map((entry) => entry.name)
  .sort(order);

if (versions.length === 0) {
  console.error("No versions in the site directory; nothing to index.");
  process.exit(1);
}

// `latest` is a copy of a version rather than a symlink, because the Pages
// artifact is a tarball and a symlink in it resolves to nothing. Which
// version it copies is recorded here so this page can say so.
const stampFile = join(site, "latest", "VERSION");
const latest = existsSync(stampFile)
  ? readFileSync(stampFile, "utf8").trim()
  : versions[0];

const older = versions
  .filter((version) => version !== latest)
  .map((version) => `        <li><a href="${version}/">${version}</a></li>`)
  .join("\n");

writeFileSync(
  join(site, "index.html"),
  `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>meo-skia-canvas — JavaScript reference</title>
    <style>
      :root { color-scheme: light dark; }
      body {
        margin: 0 auto; padding: 3rem 1.5rem; max-width: 42rem;
        font: 16px/1.6 ui-sans-serif, system-ui, -apple-system, sans-serif;
      }
      h1 { margin-bottom: 0.25rem; font-size: 1.6rem; }
      p.lede { margin-top: 0; opacity: 0.75; }
      .latest {
        display: block; margin: 1.5rem 0; padding: 1rem 1.25rem;
        border: 1px solid color-mix(in srgb, currentColor 25%, transparent);
        border-radius: 8px; text-decoration: none; font-weight: 600;
      }
      .latest span { display: block; font-weight: 400; opacity: 0.7; font-size: 0.9rem; }
      h2 { font-size: 0.85rem; text-transform: uppercase; letter-spacing: 0.06em; opacity: 0.6; }
      ul { list-style: none; padding: 0; columns: 4; }
      li { padding: 0.15rem 0; }
      a { color: inherit; }
      footer { margin-top: 2.5rem; font-size: 0.9rem; opacity: 0.7; }
      footer a { margin-right: 1rem; }
    </style>
  </head>
  <body>
    <h1>meo-skia-canvas</h1>
    <p class="lede">
      The JavaScript API reference, generated from the type declarations each
      release ships. One page per published version.
    </p>

    <a class="latest" href="latest/">
      Latest — ${latest}
      <span>Also at <code>latest/</code>, which follows the newest published release.</span>
    </a>

${older ? `    <h2>Earlier</h2>\n    <ul>\n${older}\n    </ul>` : ""}

    <footer>
      <a href="https://github.com/l7aromeo/meo-skia-canvas">Source</a>
      <a href="https://docs.rs/meo-skia-canvas">Rust reference</a>
      <a href="https://www.npmjs.com/package/meo-skia-canvas">npm</a>
    </footer>
  </body>
</html>
`,
);

console.log(`Indexed ${versions.length} version(s); latest is ${latest}.`);
