// Writes the landing page for the published reference, from the versions
// that are actually there.
//
// It is a landing page first and a version index second. Most arrivals come
// from npm, a search result or the README badge and have never seen the
// library, so the page says what it is and what it has that the obvious
// alternative does not, then routes to the reference. It does not document
// the API -- that is what it links to, and a summary here would be a second
// copy that nothing regenerates.
//
// Generated rather than committed, and generated by reading the directory
// rather than a list: a hand-kept list of versions is wrong the first time a
// release is added and nothing reports it, where this cannot describe a
// version that is not published or omit one that is.
//
// EVERY PICTURE ON THIS PAGE WAS DRAWN BY THIS LIBRARY. The hero banners come
// from `docs/generate/brand.js` and the illustrations from `docs/generate/`,
// both run by `just docs-assets`, and each showcase panel carries the code
// that produced the image beside it -- lifted from `docs/api/*.md`, where the
// two already sit together. That is the point rather than decoration: a
// graphics library whose landing page renders nothing it made is asking to be
// taken on trust. It also means the page cannot drift into showing something
// the library cannot do, because there is no source of pixels here except the
// library.
//
// The workflow copies `docs/assets/api` and `docs/assets/brand` into
// `site/assets/`; see the "Publish the illustrations" step in `docs.yml`.
// `docs/assets/gallery` is deliberately not copied: `animated-eye.*` alone is
// 19 MB across its three encodings, and the store is a git repository that
// keeps every version of every blob forever. A panel added here may reference
// anything under those two directories and needs no workflow change; one
// reaching for the gallery needs that decision revisited.
//
// Usage: node site-index.mjs <site-dir>

import { readdirSync, writeFileSync, existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

const site = process.argv[2];
if (!site || !existsSync(site)) {
  console.error("Usage: node site-index.mjs <site-dir>");
  process.exit(1);
}

/// Sorts `v5.10.0` above `v5.9.0`, which a string comparison does not.
function order(a, b) {
  const parts = (v) => v.slice(1).split(".").map(Number);
  const [x, y] = [parts(a), parts(b)];
  return y[0] - x[0] || y[1] - x[1] || y[2] - x[2];
}

const versions = readdirSync(site, { withFileTypes: true })
  .filter((entry) => entry.isDirectory() && /^v\d+\.\d+\.\d+$/.test(entry.name))
  .map((entry) => entry.name)
  .sort(order);

if (versions.length === 0) {
  console.error("No versions in the site directory; nothing to index.");
  process.exit(1);
}

// `latest` is a copy of a version rather than a symlink, because the Pages
// artifact is a tarball and a symlink in it resolves to nothing. Which
// version it copies is recorded here so this page can say so.
//
// Checked against the directory rather than believed, because it is the one
// input that is not derived from it -- and an unchecked stamp makes the page
// contradict itself at exit 0. An empty file renders an empty headline and
// lists the newest version under "Earlier releases"; a stamp naming something
// unpublished headlines a dead link and demotes the real newest. Falling back
// is right rather than fatal: the disagreement is between `latest/` and the
// version directories, and refusing to write the index does not repair it.
//
// A stamp that is absent is silent, because that is the state before the first
// one was written. A stamp that exists and does not name a published version
// is not: an empty file is the assembly step having produced nothing, which is
// the failure that looks identical to success everywhere else in this
// repository.
const stampFile = join(site, "latest", "VERSION");
const hasStamp = existsSync(stampFile);
const stamped = hasStamp ? readFileSync(stampFile, "utf8").trim() : "";
if (hasStamp && !versions.includes(stamped))
  console.warn(
    `latest/VERSION says ${stamped ? stamped : "nothing"}, which is not a ` +
      `published version. Using ${versions[0]}.`,
  );
const latest = versions.includes(stamped) ? stamped : versions[0];

const older = versions
  .filter((version) => version !== latest)
  // No `rel="nofollow"`. These were nofollowed while the plan was to keep the
  // archives out of the index; now that each one names `latest/` as its
  // canonical, a crawler reaching them is how that link gets read.
  .map((version) => `        <li><a href="${version}/">${version}</a></li>`)
  .join("\n");

const escape = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;");

// The absolute origin this page is served from, which the canonical link, the
// social cards and the sitemap all need -- a relative URL is meaningless in
// every one of them.
//
// Derived from `GITHUB_REPOSITORY` when the workflow provides it, because that
// is the same fact the store's remote is built from and cannot drift from it.
// The fallback is for a local run, where the page is being looked at rather
// than published, and a wrong origin in that copy costs nothing.
const repository = process.env.GITHUB_REPOSITORY || "l7aromeo/meo-skia-canvas";
const [owner, repoName] = repository.split("/");
const SITE = `https://${owner}.github.io/${repoName}`;

// Under about sixty characters, because Google truncates a longer one and the
// part it cuts is the end -- which is where "for Node and Rust" lives, the
// half that distinguishes this from every other canvas library.
const TITLE = "meo-skia-canvas — HTML Canvas API on Skia for Node and Rust";

// One sentence, under about 160 characters so a search result shows all of it,
// and written to be read rather than to carry keywords. Used three times --
// the meta description, the Open Graph card and the Twitter card -- from here,
// so the three cannot disagree.
const DESCRIPTION =
  "The HTML Canvas 2D API on Google's Skia, as a Rust crate and a Node addon: " +
  "float compositing, wide-gamut and HDR colour, eleven formats, GPU rendering.";

// 2560x660 is the banner as it is drawn, declared rather than rounded to what
// a card would prefer. Facebook and Twitter both crop toward their own ratio;
// stating the real size lets them do that from the true image instead of
// guessing, and a wrong width here is worse than an unfashionable one.
const OG_IMAGE = { url: `${SITE}/assets/brand/hero@2x.png`, w: 2560, h: 660 };

// Comments only, and only at the end of a line. A fuller highlighter would
// need a tokeniser: a `//` inside a string literal is a string, and `"` inside
// a comment is a comment, so anything matching both with one regex per rule
// gets one of the two wrong. Dimming comments is the whole of what a landing
// page needs, and it cannot be wrong on either case.
const highlight = (code) =>
  escape(code).replace(/(\/\/.*)$/gm, '<span class="c">$1</span>');

// The two channels, in the order the reader meets them. Both, because this
// library ships twice from one tree and a landing page naming only npm makes
// the crate look like an afterthought -- the same reason the release tags
// carry a channel prefix each rather than npm holding the bare one.
const INSTALL = [
  ["node", "Node", "npm install meo-skia-canvas"],
  ["rust", "Rust", "cargo add meo-skia-canvas"],
];

// Wide colour and a float canvas, because those are the two things a reader is
// here to find out this library has. Nothing in either is specific to a
// version, so they do not go stale between releases.
//
// The Rust half is the same program rather than a different one -- same
// canvas, same colour, same file out -- so the pair reads as one API in two
// spellings, which is the claim the tagline makes. Every name in it is checked
// against the source: `CanvasOptions` carries `color_space`, `color_type` and
// `gpu`; `PixelDepth` has `F16`; `PixelColorSpace` has `DisplayP3`; and
// `set_fill_style_css` is what takes a CSS string, where `set_fill_style`
// takes an `RgbaLinear`.
const SAMPLES = {
  node: `import { Canvas } from "meo-skia-canvas";

let canvas = new Canvas(1920, 1080, {
    colorType: "RGBAF16", // composites in float, not just reads back in it
    colorSpace: "display-p3", // or rec2020, rec2020-pq, srgb-linear, ...
  }),
  ctx = canvas.getContext("2d");

ctx.fillStyle = "oklch(70% 0.28 25)"; // outside sRGB, and kept
ctx.fillRect(0, 0, 1920, 1080);

await canvas.toFile("out.png"); // 16 bits a channel, tagged P3`,

  rust: `use meo_skia_canvas::prelude::*;

let mut canvas = Canvas::with_options(1920.0, 1080.0, CanvasOptions {
    color_type: PixelDepth::F16, // composites in float, not just reads back in it
    color_space: PixelColorSpace::DisplayP3,
    gpu: true,
})?;

let ctx = canvas.context();
ctx.set_fill_style_css("oklch(70% 0.28 25)")?; // outside sRGB, and kept
ctx.fill_rect(0.0, 0.0, 1920.0, 1080.0);

canvas.to_file("out.png", &EncodeOptions::default())?; // 16 bits a channel, tagged P3`,
};

// Each panel is an illustration this library rendered and the code that
// rendered it. The code is the block that sits beside the same image in
// `docs/api/`, trimmed to what fits: a reader who wants the surrounding prose
// follows the link under it, and one who wants to know whether the library can
// do the thing has already been answered by the picture.
const SHOWCASE = [
  {
    id: "paths",
    tab: "Path geometry",
    title: "Corners rounded, curves trimmed",
    blurb:
      "Boolean operations, <code>round</code>, <code>trim</code>, " +
      "<code>simplify</code>, <code>unwind</code>, <code>interpolate</code> " +
      "and point sampling, on any path.",
    image: "assets/api/effect-round@2x.png",
    alt: "A zig-zag path and the same path with its corners rounded off",
    href: "https://github.com/l7aromeo/meo-skia-canvas/blob/main/docs/api/path2d.md",
    code: `let spikes = new Path2D();
spikes.moveTo(50, 225);
spikes.lineTo(100, 25);
spikes.lineTo(150, 225);
spikes.lineTo(200, 25);
spikes.lineTo(250, 225);
spikes.lineTo(300, 25);

let snake = spikes.round(80);`,
  },
  {
    id: "text",
    tab: "Typography",
    title: "Text as geometry, not just ink",
    blurb:
      "<code>outlineText</code> hands back a <code>Path2D</code> you can hit " +
      "test, fill, or hand to any other path operation.",
    image: "assets/api/outlineText@2x.png",
    alt: "An ampersand rendered as a field of small squares, tinted where they fall inside the glyph",
    href: "https://github.com/l7aromeo/meo-skia-canvas/blob/main/docs/api/context.md",
    code: `ctx.textBaseline = "top";
ctx.font = "bold 140px Helvetica";
let ampersand = ctx.outlineText("&");

for (let i = 0; i < 8000; i++) {
  let x = Math.random() * 100,
    y = Math.random() * 120;
  ctx.fillStyle = ampersand.contains(x, y) ? "lightblue" : "#eee";
  ctx.fillRect(x, y, 2, 2);
}`,
  },
  {
    id: "projection",
    tab: "3D projection",
    title: "A quadrilateral, not just a matrix",
    blurb:
      "<code>createProjection</code> maps the canvas onto four corners you " +
      "name, so perspective is a transform like any other.",
    image: "assets/api/projection@2x.png",
    alt: "A flat panel drawn in perspective, receding toward the top of the frame",
    href: "https://github.com/l7aromeo/meo-skia-canvas/blob/main/docs/api/context.md",
    code: `let matrix = ctx.createProjection(quad); // use default basis
ctx.setTransform(matrix);

ctx.fillStyle = "white";
ctx.fillRect(10, 10, w - 20, h - 20);

ctx.fillStyle = "#900";
ctx.fillText("@", w / 2, h - 40);`,
  },
  {
    id: "compositing",
    tab: "Compositing",
    title: "Every operator, including three the standard omits",
    blurb:
      "The full <code>globalCompositeOperation</code> set, plus " +
      "<code>clear</code>, <code>destination</code> and <code>modulate</code>, " +
      "separated in the declared type so you know which half you are using.",
    image: "assets/api/operations@2x.png",
    alt: "A grid of two overlapping shapes combined under each compositing operator",
    href: "https://github.com/l7aromeo/meo-skia-canvas/blob/main/docs/api/path2d.md",
    code: `let knockout = rect.complement(oval),
  overlap = rect.intersect(oval),
  union = rect.union(oval),
  cutout = rect.difference(oval);`,
  },
  {
    id: "animation",
    tab: "Animation",
    title: "Pages are frames",
    blurb:
      "150 pages on a Display&nbsp;P3 canvas, written as one AVIF at 60&nbsp;fps. " +
      "The four formats that carry a clock take the same call, and an animation " +
      "read back reports its own <code>frames</code> and <code>delays</code>.",
    image: "assets/gallery/animated-eye.avif",
    alt: "An eye blinking and glancing, drawn and encoded by this library",
    href: "https://github.com/l7aromeo/meo-skia-canvas/blob/main/examples/node/animated-eye.js",
    code: `const canvas = new Canvas(640, 500, {
  colorSpace: "display-p3",
  gpu: true,
});

// ... one ctx.newPage() per frame ...

canvas.toFileSync("eye.avif", { fps: 60, loop: 0 });`,
  },
  {
    id: "texture",
    tab: "Textures",
    title: "Fills that are vectors, not tiles",
    blurb:
      "<code>createTexture</code> fills with a path repeated on a grid you " +
      "control &mdash; it scales with the transform, where a bitmap " +
      "<code>Pattern</code> resamples.",
    image: "assets/api/createTexture@2x.png",
    alt: "Shapes filled with a repeating vector hatch pattern",
    href: "https://github.com/l7aromeo/meo-skia-canvas/blob/main/docs/api/context.md",
    code: `let lines = new Path2D();
lines.moveTo(0, 0);
lines.lineTo(10, 10);

ctx.fillStyle = ctx.createTexture([10, 10], {
  path: lines,
  line: 2,
});`,
  },
];

const tabs = SHOWCASE.map(
  (panel, i) =>
    `          <button role="tab" id="tab-${panel.id}" aria-controls="panel-${panel.id}"` +
    ` aria-selected="${i === 0 ? "true" : "false"}" tabindex="${i === 0 ? "0" : "-1"}">` +
    `${panel.tab}</button>`,
).join("\n");

const panels = SHOWCASE.map(
  (panel, i) => `        <section
          class="panel"
          role="tabpanel"
          id="panel-${panel.id}"
          aria-labelledby="tab-${panel.id}"
          ${i === 0 ? "" : "data-secondary"}
        >
          <figure>
            <img src="${panel.image}" alt="${panel.alt}" loading="lazy" decoding="async" />
            <figcaption>Rendered by this library.</figcaption>
          </figure>
          <div class="panel-copy">
            <h3>${panel.title}</h3>
            <p>${panel.blurb}</p>
            <pre><code>${highlight(panel.code)}</code></pre>
            <a class="more" href="${panel.href}">Read the guide &rarr;</a>
          </div>
        </section>`,
).join("\n");

// What a reader who has never used this library needs in the first screen.
// Every claim here is one the README states and the declarations carry; if
// one stops being true, it is wrong in three places at once, which is the
// point -- a claim only this page makes has nothing to check it.
const features = [
  [
    "Float compositing",
    "<code>RGBAF16</code> and <code>RGBAF32</code> composite in float rather " +
      "than merely reading back in it, so stacked translucent layers do not " +
      "accumulate rounding error.",
  ],
  [
    "Wide gamut and HDR transfer functions",
    "Fifteen names across eight spaces &mdash; sRGB, Display P3, Rec.&nbsp;2020, " +
      "HDR10 (PQ), HLG and linear variants. A canvas composites in the space " +
      "you name and exports tagged with it.",
  ],
  [
    "CSS Color 4, and OkLab gradients",
    "<code>oklch()</code>, <code>lab()</code> and <code>color()</code> parse " +
      "wherever a colour is taken, and a gradient interpolates in the space " +
      "you choose &mdash; <code>oklab</code> holds lightness where sRGB goes " +
      "muddy in the middle.",
  ],
  [
    "Eleven export formats",
    "PNG, JPEG, WebP, GIF, APNG, TIFF, ICO, BMP, AVIF, PDF and SVG. Pages are " +
      "frames: the four formats that carry a clock write animations, and an " +
      "animation read back reports its own frames and delays.",
  ],
  [
    "Typography that goes past <code>fillText</code>",
    "Variable font axes, OpenType features, word wrap with per-line metrics, " +
      "and a <code>ParagraphBuilder</code> for rich text with mixed styles, " +
      "per-run shadows and hit testing.",
  ],
  [
    "GPU rendering",
    "Metal on macOS, Vulkan elsewhere, chosen per canvas. " +
      "<code>canvas.engine</code> reports which backend took it, the adapter, " +
      "and why the GPU was declined when it was.",
  ],
  [
    "Path geometry and filters",
    "Boolean operations, <code>trim</code>, <code>interpolate</code>, 3D " +
      "projection and vector textures, plus the CSS filter set and " +
      "CanvasKit's <code>ColorFilter</code>, <code>ImageFilter</code>, " +
      "<code>MaskFilter</code> and <code>Shader</code>.",
  ],
  [
    "On-screen as well as off",
    "<code>Window</code> and <code>App</code> give a browser-like event loop, " +
      "from Rust as well as Node.",
  ],
]
  .map(
    ([title, body]) =>
      `      <li>\n        <h3>${title}</h3>\n        <p>${body}</p>\n      </li>`,
  )
  .join("\n");

const FORMAT_NAMES = [
  "PNG",
  "JPEG",
  "WebP",
  "GIF",
  "APNG",
  "TIFF",
  "ICO",
  "BMP",
  "AVIF",
  "PDF",
  "SVG",
];

// Rendered twice -- once by the install line, once above the sample -- because
// the two are far enough apart that a reader who reaches the sample has lost
// sight of the control. Both groups are driven by `data-lang` rather than by
// identity, so clicking either moves the install command and the sample
// together and leaves both rows agreeing about which language is showing.
const langTabs = (extraClass) =>
  INSTALL.map(
    ([id, label], i) =>
      `        <button data-lang="${id}" class="lang-tab${extraClass}"${i === 0 ? ' aria-current="true"' : ""}>${label}</button>`,
  ).join("\n");

const installTabs = langTabs("");

// Built here rather than nested inside the page template. Two of these used to
// be a template literal inside a `${...}` of the outer one, which reads fine
// and defeated `check-stacked-docs`: its scanner has to decide whether each
// `/` opens a regular expression or divides, and a nesting it mis-tracks sends
// it into a string that never closes, leaving the rest of the file unscanned
// while the check still reported success. Flat strings cost nothing here and
// keep that scanner honest.
const formats = FORMAT_NAMES.map(
  (name) => "          <li>" + name + "</li>",
).join("\n");

const olderSection = older
  ? [
      '    <section class="band">',
      '      <div class="wrap">',
      "        <h2>Earlier releases</h2>",
      '        <p class="sub">',
      "          Every published version keeps its own reference.",
      "          <code>latest/</code> always follows the newest.",
      "        </p>",
      '        <ul class="versions">',
      older,
      "        </ul>",
      "      </div>",
      "    </section>",
    ].join("\n")
  : "";

const installLines = INSTALL.map(
  ([id, , command], i) =>
    `        <div class="install-line" data-lang="${id}"${i === 0 ? "" : " data-secondary"}>
          <code>${command}</code>
          <button class="copy" data-copy="${command}" aria-label="Copy ${command}">Copy</button>
        </div>`,
).join("\n");

const sampleBlocks = INSTALL.map(
  ([id], i) =>
    `      <pre class="sample" data-lang="${id}"${i === 0 ? "" : " data-secondary"}><code>${highlight(SAMPLES[id])}</code></pre>`,
).join("\n");

writeFileSync(
  join(site, "index.html"),
  `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${TITLE}</title>
    <meta name="description" content="${DESCRIPTION}" />

    <!--
      Canonical, because this page is reachable at the origin with and without
      a trailing slash and through the repository's own Pages alias. Naming one
      of them keeps a search engine from splitting the page's standing across
      several URLs that are the same document.
    -->
    <link rel="canonical" href="${SITE}/" />

    <!--
      An SVG favicon written beside this page rather than the 84 KB banner the
      icon used to point at: a browser fetches the icon on every visit, and a
      banner scaled to 16 px is both slow and unreadable.
    -->
    <link rel="icon" href="favicon.svg" type="image/svg+xml" />
    <meta name="theme-color" content="#0b1220" />

    <meta property="og:type" content="website" />
    <meta property="og:site_name" content="meo-skia-canvas" />
    <meta property="og:url" content="${SITE}/" />
    <meta property="og:title" content="${TITLE}" />
    <meta property="og:description" content="${DESCRIPTION}" />
    <meta property="og:image" content="${OG_IMAGE.url}" />
    <meta property="og:image:width" content="${OG_IMAGE.w}" />
    <meta property="og:image:height" content="${OG_IMAGE.h}" />
    <meta
      property="og:image:alt"
      content="The meo-skia-canvas wordmark over overlapping translucent shapes"
    />

    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="${TITLE}" />
    <meta name="twitter:description" content="${DESCRIPTION}" />
    <meta name="twitter:image" content="${OG_IMAGE.url}" />

    <!--
      Structured data as SoftwareSourceCode rather than SoftwareApplication:
      this is a library someone installs into their own program, not an
      application anyone runs, and describing it as the latter would put an
      operating system and a price where neither belongs. The
      programmingLanguage field carries both languages because the package
      genuinely ships as both.
    -->
    <script type="application/ld+json">
      {
        "@context": "https://schema.org",
        "@type": "SoftwareSourceCode",
        "name": "meo-skia-canvas",
        "description": "${DESCRIPTION}",
        "url": "${SITE}/",
        "codeRepository": "https://github.com/${repository}",
        "programmingLanguage": ["Rust", "JavaScript", "TypeScript"],
        "runtimePlatform": ["Node.js", "Rust"],
        "license": "https://opensource.org/licenses/MIT",
        "version": "${latest.slice(1)}",
        "image": "${OG_IMAGE.url}"
      }
    </script>
    <style>
      /* The palette is the one the banners are drawn with, from
         docs/generate/brand.js by way of scripts/typedoc/theme.css, so the
         page and the pictures on it cannot disagree about the brand. */
      :root {
        color-scheme: light dark;

        --paper: #ffffff;
        --tile: #f2f4f8;
        --ink: #101828;
        --muted: #475467;
        --handle: #98a2b3;

        --cyan: #22d3ee;
        --indigo: #6366f1;
        --pink: #ec4899;
        --amber: #f59e0b;

        --accent: #4f46e5;
        --rule: color-mix(in srgb, var(--ink) 12%, transparent);
        --hush: color-mix(in srgb, var(--ink) 5%, transparent);
        --shadow: 0 1px 2px rgba(16, 24, 40, 0.06),
          0 8px 24px -12px rgba(16, 24, 40, 0.18);
      }

      @media (prefers-color-scheme: dark) {
        :root {
          --paper: #0b1220;
          --tile: #141d2f;
          --ink: #f8fafc;
          --muted: #94a3b8;
          --handle: #5b6b85;
          --accent: #818cf8;
          --rule: color-mix(in srgb, var(--ink) 14%, transparent);
          --hush: color-mix(in srgb, var(--ink) 6%, transparent);
          --shadow: 0 1px 2px rgba(0, 0, 0, 0.4),
            0 8px 24px -12px rgba(0, 0, 0, 0.6);
        }
      }

      * { box-sizing: border-box; }

      body {
        margin: 0;
        padding: 0;
        background: var(--paper);
        color: var(--ink);
        font: 16px/1.6 ui-sans-serif, system-ui, -apple-system, "Segoe UI",
          sans-serif;
        -webkit-font-smoothing: antialiased;
      }

      .wrap { max-width: 62rem; margin: 0 auto; padding: 0 1.5rem; }

      a { color: var(--accent); }
      code {
        font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
        font-size: 0.9em;
      }

      /* ---- header ---- */

      header.bar {
        position: sticky; top: 0; z-index: 10;
        background: color-mix(in srgb, var(--paper) 86%, transparent);
        backdrop-filter: blur(10px);
        border-bottom: 1px solid var(--rule);
      }
      header.bar .wrap {
        display: flex; align-items: center; gap: 1.25rem;
        height: 3.5rem;
      }
      .wordmark {
        font-weight: 700; letter-spacing: -0.015em; text-decoration: none;
        color: inherit; margin-right: auto;
      }
      .wordmark .dot {
        display: inline-block; width: 0.5rem; height: 0.5rem;
        margin-right: 0.5rem; border-radius: 50%;
        background: linear-gradient(135deg, var(--cyan), var(--indigo));
      }
      header.bar nav a {
        color: var(--muted); text-decoration: none; font-size: 0.9rem;
        font-weight: 500; margin-left: 1.15rem;
      }
      header.bar nav a:hover { color: var(--ink); }
      @media (max-width: 40rem) {
        header.bar nav a.optional { display: none; }
      }

      /* ---- hero ---- */

      .hero { padding: 4rem 0 1rem; position: relative; overflow: hidden; }
      .hero::before {
        content: ""; position: absolute; inset: -40% 0 auto;
        height: 30rem; pointer-events: none; z-index: -1;
        background:
          radial-gradient(38rem 20rem at 18% 34%,
            color-mix(in srgb, var(--indigo) 20%, transparent), transparent 70%),
          radial-gradient(30rem 18rem at 76% 20%,
            color-mix(in srgb, var(--cyan) 16%, transparent), transparent 70%);
      }
      .eyebrow {
        display: inline-flex; align-items: center; gap: 0.5rem;
        padding: 0.3rem 0.7rem; border-radius: 999px;
        border: 1px solid var(--rule); background: var(--hush);
        font-size: 0.8rem; font-weight: 600; color: var(--muted);
        text-decoration: none;
      }
      .eyebrow b { color: var(--accent); }
      h1 {
        margin: 1.1rem 0 0.4rem;
        font-size: clamp(2.1rem, 5.2vw, 3.2rem);
        line-height: 1.08; letter-spacing: -0.03em;
      }
      p.tagline {
        margin: 0 0 1rem; font-size: clamp(1.05rem, 2.2vw, 1.35rem);
        font-weight: 600; color: var(--muted);
      }
      p.lede { margin: 0; max-width: 42rem; color: var(--muted); }

      /* ---- install ---- */

      .install { margin: 2rem 0 0; }
      .lang-tabs { display: flex; gap: 0.4rem; margin-bottom: 0.6rem; }
      .lang-tab {
        border: 1px solid var(--rule); background: transparent;
        color: var(--muted); border-radius: 999px;
        padding: 0.25rem 0.8rem; font: inherit; font-size: 0.82rem;
        font-weight: 600; cursor: pointer;
      }
      .lang-tab[aria-current="true"] {
        background: var(--ink); color: var(--paper); border-color: var(--ink);
      }
      .install-line {
        display: flex; align-items: center; gap: 1rem;
        padding: 0.7rem 0.7rem 0.7rem 1rem; max-width: 30rem;
        border: 1px solid var(--rule); border-radius: 10px;
        background: var(--tile);
      }
      .install-line code { flex: 1; font-size: 0.9rem; }
      .copy {
        border: 1px solid var(--rule); background: var(--paper);
        color: var(--muted); border-radius: 7px; padding: 0.25rem 0.6rem;
        font: inherit; font-size: 0.78rem; font-weight: 600; cursor: pointer;
      }
      .copy:hover { color: var(--ink); }

      .cta-row {
        display: flex; flex-wrap: wrap; gap: 0.75rem; margin-top: 1.5rem;
      }
      .cta {
        display: inline-flex; align-items: baseline; gap: 0.5rem;
        padding: 0.7rem 1.1rem; border-radius: 10px;
        text-decoration: none; font-weight: 600; font-size: 0.95rem;
        background: var(--ink); color: var(--paper);
        box-shadow: var(--shadow);
      }
      .cta.secondary {
        background: transparent; color: var(--ink);
        border: 1px solid var(--rule); box-shadow: none;
      }
      .cta small { font-weight: 500; opacity: 0.65; font-size: 0.82em; }

      /* ---- banner ---- */

      .banner { margin: 2.5rem 0 0; }
      .banner img {
        display: block; width: 100%; height: auto; border-radius: 14px;
        border: 1px solid var(--rule); box-shadow: var(--shadow);
      }
      .banner figcaption {
        margin-top: 0.6rem; font-size: 0.8rem; color: var(--handle);
      }
      figure { margin: 0; }

      /* ---- section furniture ---- */

      section.band { padding: 4rem 0 0; }
      h2 {
        margin: 0 0 0.4rem; font-size: clamp(1.4rem, 3vw, 1.9rem);
        letter-spacing: -0.02em;
      }
      .band > .wrap > p.sub {
        margin: 0 0 1.75rem; color: var(--muted); max-width: 40rem;
      }

      /* ---- showcase ---- */

      .tablist {
        display: flex; gap: 0.4rem; overflow-x: auto; padding-bottom: 0.5rem;
        margin-bottom: 1.25rem; border-bottom: 1px solid var(--rule);
        scrollbar-width: none;
      }
      .tablist::-webkit-scrollbar { display: none; }
      .tablist button {
        flex: 0 0 auto; border: 0; background: transparent; color: var(--muted);
        font: inherit; font-size: 0.9rem; font-weight: 600; cursor: pointer;
        padding: 0.45rem 0.75rem; border-radius: 8px 8px 0 0;
        border-bottom: 2px solid transparent; margin-bottom: -0.55rem;
      }
      .tablist button[aria-selected="true"] {
        color: var(--ink); border-bottom-color: var(--accent);
      }

      .panel {
        display: grid; gap: 2rem; align-items: start;
        grid-template-columns: minmax(0, 1.05fr) minmax(0, 1fr);
      }
      @media (max-width: 48rem) {
        .panel { grid-template-columns: 1fr; }
      }
      .panel img {
        display: block; width: 100%; height: auto; border-radius: 12px;
        background: var(--tile); border: 1px solid var(--rule);
      }
      .panel figcaption {
        margin-top: 0.5rem; font-size: 0.78rem; color: var(--handle);
      }
      .panel-copy h3 { margin: 0 0 0.35rem; font-size: 1.15rem; }
      .panel-copy > p { margin: 0 0 1rem; color: var(--muted); font-size: 0.95rem; }
      a.more { font-size: 0.88rem; font-weight: 600; text-decoration: none; }
      a.more:hover { text-decoration: underline; }

      /* Without JavaScript every panel stays on the page, stacked, and the
         tabs do nothing rather than hiding content nobody can reach. The
         enhancement is additive: the data-secondary attribute only hides once
         the script has marked the document. */
      html.js [data-secondary] { display: none; }
      html.js .panel[data-secondary] { display: none; }

      /* ---- code ---- */

      pre {
        margin: 0; padding: 1rem 1.15rem; overflow-x: auto;
        background: var(--tile); border: 1px solid var(--rule);
        border-radius: 10px;
        font: 0.83rem/1.55 ui-monospace, SFMono-Regular, Menlo, monospace;
      }
      pre .c { color: var(--handle); }

      /* ---- features ---- */

      ul.features {
        list-style: none; margin: 0; padding: 0; display: grid;
        gap: 1.5rem 2rem;
        grid-template-columns: repeat(auto-fit, minmax(17rem, 1fr));
      }
      ul.features h3 { margin: 0 0 0.25rem; font-size: 1rem; }
      ul.features h3::before {
        content: ""; display: inline-block; width: 0.4rem; height: 0.4rem;
        margin-right: 0.5rem; border-radius: 50%; vertical-align: middle;
        background: linear-gradient(135deg, var(--cyan), var(--indigo));
      }
      ul.features p { margin: 0; font-size: 0.92rem; color: var(--muted); }

      /* ---- formats ---- */

      ul.formats {
        list-style: none; margin: 0; padding: 0;
        display: flex; flex-wrap: wrap; gap: 0.5rem;
      }
      ul.formats li {
        padding: 0.3rem 0.7rem; border-radius: 999px;
        border: 1px solid var(--rule); background: var(--hush);
        font-size: 0.82rem; font-weight: 600; color: var(--muted);
      }

      /* ---- versions ---- */

      /* auto-fill rather than a fixed count: the list is as many columns as
         fit, down to one on a phone, without a breakpoint to keep in step
         with however many versions are published. */
      ul.versions {
        list-style: none; margin: 0; padding: 0; display: grid;
        gap: 0.2rem 1rem;
        grid-template-columns: repeat(auto-fill, minmax(7rem, 1fr));
        font-size: 0.9rem;
      }

      /* ---- footer ---- */

      footer {
        margin-top: 4rem; padding: 2rem 0 3rem;
        border-top: 1px solid var(--rule); font-size: 0.9rem;
        color: var(--muted);
      }
      footer .wrap { display: flex; flex-wrap: wrap; gap: 0.5rem 1.5rem; }
      footer a { margin-right: 0.25rem; }
      footer .spacer { margin-left: auto; }

      @media (prefers-reduced-motion: no-preference) {
        .panel { animation: rise 0.25s ease-out; }
        @keyframes rise {
          from { opacity: 0; transform: translateY(4px); }
          to { opacity: 1; transform: none; }
        }
      }
    </style>
  </head>
  <body>
    <header class="bar">
      <div class="wrap">
        <a class="wordmark" href="./"><span class="dot"></span>meo-skia-canvas</a>
        <nav>
          <a href="latest/">Reference</a>
          <a class="optional" href="https://github.com/l7aromeo/meo-skia-canvas/tree/main/docs">Guide</a>
          <a class="optional" href="https://docs.rs/meo-skia-canvas">docs.rs</a>
          <a href="https://github.com/l7aromeo/meo-skia-canvas">GitHub</a>
        </nav>
      </div>
    </header>

    <div class="hero">
      <div class="wrap">
        <a class="eyebrow" href="latest/">JavaScript reference &mdash; <b>${latest}</b></a>
        <h1>The HTML Canvas 2D API, on Skia.</h1>
        <p class="tagline">One implementation, two surfaces: a Rust crate and a Node addon.</p>
        <p class="lede">
          Google's Skia underneath, so output matches Chrome's
          <code>&lt;canvas&gt;</code> closely &mdash; and then a good deal a browser
          canvas cannot do. The same objects and the same calls from Rust, in
          Rust's own spelling, argument for argument.
        </p>

        <div class="install">
          <div class="lang-tabs">
${installTabs}
          </div>
${installLines}
        </div>

        <div class="cta-row">
          <a class="cta" href="latest/">Open the reference <small>${latest}</small></a>
          <a class="cta secondary" href="https://github.com/l7aromeo/meo-skia-canvas/tree/main/docs">Read the guide</a>
        </div>

        <figure class="banner">
          <picture>
            <source
              srcset="assets/brand/hero-dark@2x.png"
              media="(prefers-color-scheme: dark)"
            />
            <img
              src="assets/brand/hero@2x.png"
              alt="The meo-skia-canvas wordmark over overlapping translucent shapes in cyan, indigo, pink and amber"
            />
          </picture>
          <figcaption>Drawn by this library, by <code>just docs-assets</code>.</figcaption>
        </figure>
      </div>
    </div>

    <section class="band">
      <div class="wrap">
        <h2>What it draws</h2>
        <p class="sub">
          Every image below was rendered by this library, beside the code that
          rendered it.
        </p>

        <div class="tablist" role="tablist" aria-label="Capabilities">
${tabs}
        </div>

${panels}
      </div>
    </section>

    <section class="band">
      <div class="wrap">
        <h2>Wide colour, in seven lines</h2>
        <p class="sub">
          The same program in both spellings. A float canvas in a wide space,
          filled with a colour sRGB cannot hold, written out tagged.
        </p>
        <div class="lang-tabs">
${langTabs("")}
        </div>
${sampleBlocks}
      </div>
    </section>

    <section class="band">
      <div class="wrap">
        <h2>What you get</h2>
        <p class="sub">
          Claims the README states and the type declarations carry, so none of
          them lives only here.
        </p>
        <ul class="features">
${features}
        </ul>
      </div>
    </section>

    <section class="band">
      <div class="wrap">
        <h2>Eleven export formats</h2>
        <p class="sub">
          Pages are frames: the four that carry a clock write animations, and an
          animation read back reports its own frames and delays.
        </p>
        <ul class="formats">
${formats}
        </ul>
      </div>
    </section>

${olderSection}

    <footer>
      <div class="wrap">
        <a href="https://github.com/l7aromeo/meo-skia-canvas#readme">Guide and README</a>
        <a href="https://docs.rs/meo-skia-canvas">Rust reference</a>
        <a href="https://www.npmjs.com/package/meo-skia-canvas">npm</a>
        <a href="https://crates.io/crates/meo-skia-canvas">crates.io</a>
        <a href="https://github.com/l7aromeo/meo-skia-canvas">Source</a>
        <span class="spacer">MIT licensed.</span>
      </div>
    </footer>

    <script>
      // Marks the document before the panels paint, so the ones the tablist
      // hides are never briefly visible. Everything below is additive: with
      // this script blocked, every panel and both languages stay on the page.
      document.documentElement.className = "js";

      (function () {
        var tablist = document.querySelector(".tablist");
        var tabs = tablist ? [].slice.call(tablist.querySelectorAll("button")) : [];

        function select(tab) {
          tabs.forEach(function (other) {
            var on = other === tab;
            other.setAttribute("aria-selected", on ? "true" : "false");
            other.tabIndex = on ? 0 : -1;
            var panel = document.getElementById(
              other.getAttribute("aria-controls")
            );
            if (panel) {
              if (on) panel.removeAttribute("data-secondary");
              else panel.setAttribute("data-secondary", "");
            }
          });
        }

        tabs.forEach(function (tab, i) {
          tab.addEventListener("click", function () {
            select(tab);
          });
          // Arrow keys move between tabs, which is what a tablist is expected
          // to do and what a row of buttons does not do on its own.
          tab.addEventListener("keydown", function (event) {
            var step =
              event.key === "ArrowRight" ? 1 : event.key === "ArrowLeft" ? -1 : 0;
            if (!step) return;
            event.preventDefault();
            var next = tabs[(i + step + tabs.length) % tabs.length];
            select(next);
            next.focus();
          });
        });

        // The install command and the sample move together: a reader who came
        // for the crate should not have to say so twice.
        var langTabs = [].slice.call(document.querySelectorAll(".lang-tab"));
        langTabs.forEach(function (tab) {
          tab.addEventListener("click", function () {
            var lang = tab.getAttribute("data-lang");
            // Matched on the language rather than on the button, because the
            // row is rendered twice: keying on identity would mark the clicked
            // button and clear its twin, leaving the two rows disagreeing about
            // which language the page is showing.
            langTabs.forEach(function (other) {
              if (other.getAttribute("data-lang") === lang)
                other.setAttribute("aria-current", "true");
              else other.removeAttribute("aria-current");
            });
            [].slice
              .call(document.querySelectorAll("[data-lang]"))
              .forEach(function (el) {
                if (el.classList.contains("lang-tab")) return;
                if (el.getAttribute("data-lang") === lang)
                  el.removeAttribute("data-secondary");
                else el.setAttribute("data-secondary", "");
              });
          });
        });

        // Clipboard access is refused on an insecure origin and can be denied
        // on a secure one, so the failure is reported rather than swallowed --
        // a button that silently does nothing reads as a broken page.
        document.addEventListener("click", function (event) {
          var button = event.target.closest && event.target.closest(".copy");
          if (!button) return;
          var text = button.getAttribute("data-copy");
          var restore = function (label) {
            button.textContent = label;
            setTimeout(function () {
              button.textContent = "Copy";
            }, 1600);
          };
          if (!navigator.clipboard) return restore("Copy failed");
          navigator.clipboard.writeText(text).then(
            function () {
              restore("Copied");
            },
            function () {
              restore("Copy failed");
            }
          );
        });
      })();
    </script>
  </body>
</html>
`,
);

// A favicon that is 400 bytes rather than 84 KB, drawn from the same two brand
// colours the wordmark uses. SVG because every browser that matters takes one
// and it stays sharp at any size; the alternative was the banner scaled to
// 16 px, which is a smear.
writeFileSync(
  join(site, "favicon.svg"),
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
  <defs>
    <linearGradient id="g" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="#22d3ee" />
      <stop offset="1" stop-color="#6366f1" />
    </linearGradient>
  </defs>
  <rect width="32" height="32" rx="7" fill="#0b1220" />
  <path
    d="M8 22 C 12 8, 20 26, 24 11"
    fill="none"
    stroke="url(#g)"
    stroke-width="4"
    stroke-linecap="round"
  />
</svg>
`,
);

// EVERY VERSION IS A NEAR-COPY OF EVERY OTHER. Thirteen published references,
// each several hundred pages, differing by a few signatures -- which to a
// search engine is one document at thirteen addresses. Left alone it splits
// the site's standing across all of them and can rank a two-year-old page
// above the current one.
//
// The answer is a canonical link on each archived page rather than a
// `Disallow` here, and the two cannot both be used: a page that is not
// crawled is a page whose canonical is never read, so disallowing the version
// directories would cancel the very thing that consolidates them.
// `canonicalise.mjs` writes those links after the site is assembled; this file
// stays out of its way.
//
// Nothing is disallowed, then. The version directories are crawlable, each
// archived page names its counterpart under `latest/` as the canonical, and a
// page `latest/` no longer has stays self-canonical because it really is the
// only copy of itself.
writeFileSync(
  join(site, "robots.txt"),
  `User-agent: *
Allow: /

Sitemap: ${SITE}/sitemap.xml
`,
);

// Two URLs, because two are all that should be crawled: this page and the
// current reference. A crawler reaching `latest/` follows its own navigation
// from there, so listing several hundred generated pages would add nothing a
// link does not already give.
writeFileSync(
  join(site, "sitemap.xml"),
  `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>${SITE}/</loc>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>${SITE}/latest/</loc>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
</urlset>
`,
);

console.log(`Indexed ${versions.length} version(s); latest is ${latest}.`);
